version: '3.8'

services:
  rest-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Development service with volume mounting
  rest-api-dev:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py
    profiles:
      - dev
